services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - .env
    networks:
      - postgres

  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - '8080:80'
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - .env
    networks:
      - postgres

  nestjs:
    build:
      context: .
    container_name: nestjs
    depends_on:
      - postgres
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - .:/usr/src/app # Mount the local project directory to the container
    working_dir: /usr/src/app
    command: ['npm', 'run', 'start:dev']
    networks:
      - postgres
    user: root


networks:
  postgres:
    driver: bridge